name: Debug Pipeline

on:
  push:
    branches: ["main"]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Files
        run: |
          echo "Listing files:"
          ls -la